spring.application.name=mensajeria
server.port=8056

spring.datasource.url=jdbc:mysql://localhost:3307/db_mensajeria?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:UnaClaveSuperSecretaYMuyLargaParaPoderFirmarElTokenCorrectamente12345}

internal.api.token=${INTERNAL_API_TOKEN:dev-internal-token}

ms.administracion.base-url=${MS_ADMINISTRACION_BASE_URL:http://localhost:8052}
ms.auth.base-url=${MS_AUTH_BASE_URL:http://localhost:8051}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
