spring.application.name=conducta
server.port=8055

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_conducta}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=UnaClaveSuperSecretaYMuyLargaParaPoderFirmarElTokenCorrectamente12345

ms.administracion.base-url=${MS_ADMINISTRACION_BASE_URL:http://localhost:8052}
ms.autenticacion.base-url=${MS_AUTENTICACION_BASE_URL:http://localhost:8051}
ms.mensajeria.base-url=${MS_MENSAJERIA_BASE_URL:http://localhost:8056}
internal.api.token=${INTERNAL_API_TOKEN:dev-internal-token}
