spring.application.name=conducta
server.port=8055

spring.datasource.url=jdbc:mysql://localhost:3307/db_conducta?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

jwt.secret=UnaClaveSuperSecretaYMuyLargaParaPoderFirmarElTokenCorrectamente12345

ms.administracion.base-url=${MS_ADMINISTRACION_BASE_URL:http://localhost:8052}
ms.autenticacion.base-url=${MS_AUTENTICACION_BASE_URL:http://localhost:8051}
ms.mensajeria.base-url=${MS_MENSAJERIA_BASE_URL:http://localhost:8056}
internal.api.token=${INTERNAL_API_TOKEN:dev-internal-token}
