server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    # API gateway interno (mismo origen para el SPA)
    location /auth/ {
        proxy_pass http://auth-api:8051/auth/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/admin/ {
        proxy_pass http://admin-api:8052/api/admin/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/docentes/ {
        proxy_pass http://admin-api:8052/api/docentes/;
        proxy_http_version 1.1;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/apoderados/ {
        proxy_pass http://admin-api:8052/api/apoderados/;
        proxy_http_version 1.1;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/alumnos/ {
        proxy_pass http://admin-api:8052/api/alumnos/;
        proxy_http_version 1.1;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/permisos/ {
        proxy_pass http://admin-api:8052/api/permisos/;
        proxy_http_version 1.1;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/academico/ {
        proxy_pass http://academico-api:8053/api/academico/;
        proxy_http_version 1.1;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/asistencia/ {
        proxy_pass http://asistencia-api:8054/api/asistencia/;
        proxy_http_version 1.1;
        proxy_set_header Authorization $http_authorization;
        proxy_buffering off;
        proxy_cache off;
    }

    location /api/conducta/ {
        proxy_pass http://conducta-api:8055/api/conducta/;
        proxy_http_version 1.1;
        proxy_set_header Authorization $http_authorization;
    }

    location /api/mensajes/ {
        proxy_pass http://mensajeria-api:8056/api/mensajes/;
        proxy_http_version 1.1;
        proxy_set_header Authorization $http_authorization;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
