CREATE DATABASE IF NOT EXISTS db_usuarios;
CREATE DATABASE IF NOT EXISTS db_administracion;
CREATE DATABASE IF NOT EXISTS db_academico;
CREATE DATABASE IF NOT EXISTS db_asistencia;
CREATE DATABASE IF NOT EXISTS db_conducta;
CREATE DATABASE IF NOT EXISTS db_mensajeria;
