#!/usr/bin/env python3
"""Migrate tables from MySQL to PostgreSQL/Supabase.

Usage:
  1. Install dependencies:
     pip install pymysql psycopg2-binary

  2. Configure environment variables:
     export MYSQL_HOST=localhost
     export MYSQL_PORT=3306
     export MYSQL_USER=root
     export MYSQL_PASSWORD=secret
     export MYSQL_DATABASE=db_usuarios

     export POSTGRES_HOST=localhost
     export POSTGRES_PORT=5432
     export POSTGRES_USER=postgres
     export POSTGRES_PASSWORD=postgres
     export POSTGRES_DB=db_usuarios

  3. Run:
     python migrate_mysql_to_postgres.py

Optional:
  export TABLES='users,orders'  # comma-separated list of tables to migrate
  export SKIP_TABLES='schema_migrations'  # comma-separated list to skip
"""

from __future__ import annotations

import os
import sys
from typing import Any, Dict, List, Optional, Sequence, Tuple

import pymysql
import psycopg2
from psycopg2 import sql
from psycopg2.extras import RealDictCursor


def get_env(name: str, default: Optional[str] = None) -> Optional[str]:
    value = os.getenv(name)
    if value is None:
        return default
    return value


def parse_csv_list(value: Optional[str]) -> set[str]:
    if not value:
        return set()
    return {item.strip() for item in value.split(',') if item.strip()}


def quote_ident(name: str) -> sql.Composed:
    return sql.Identifier(name)


def mysql_to_pg_type(column_type: str, data_type: str, nullable: str, column_key: str, column_default: Optional[str], extra: str) -> Tuple[str, bool]:
    raw = (column_type or data_type or '').lower()
    data_type = (data_type or '').lower()

    if data_type in {'tinyint', 'smallint', 'mediumint', 'int', 'integer', 'bigint'}:
        if 'unsigned' in raw and data_type in {'int', 'integer', 'bigint'}:
            return 'BIGINT', False
        if data_type == 'bigint':
            return 'BIGINT', False
        if data_type in {'tinyint', 'smallint', 'mediumint', 'int', 'integer'}:
            return 'INTEGER', False

    if data_type in {'bool', 'boolean'} or (data_type == 'tinyint' and '1' in raw):
        return 'BOOLEAN', False

    if data_type in {'decimal', 'numeric'}:
        return 'NUMERIC', False

    if data_type in {'float', 'double', 'real'}:
        return 'DOUBLE PRECISION', False

    if data_type in {'varchar', 'char', 'tinytext', 'text', 'mediumtext', 'longtext', 'enum', 'set'}:
        return 'TEXT', False

    if data_type in {'date'}:
        return 'DATE', False

    if data_type in {'datetime', 'timestamp'}:
        return 'TIMESTAMP', False

    if data_type in {'time'}:
        return 'TIME', False

    if data_type in {'json'}:
        return 'JSONB', False

    if data_type in {'binary', 'varbinary', 'blob', 'mediumblob', 'longblob'}:
        return 'BYTEA', False

    return 'TEXT', False


def get_mysql_columns(connection, schema: str, table: str) -> List[Dict[str, Any]]:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name, data_type, column_type, is_nullable, column_key, column_default, extra
            FROM information_schema.columns
            WHERE table_schema = %s AND table_name = %s
            ORDER BY ordinal_position
            """,
            (schema, table),
        )
        return list(cursor.fetchall())


def create_postgres_table(pg_conn, table: str, columns: List[Dict[str, Any]]) -> None:
    stmt_parts: List[str] = [f'CREATE TABLE IF NOT EXISTS {quote_ident(table)} (']
    column_defs: List[str] = []
    pk_columns: List[str] = []

    for col in columns:
        name = col['COLUMN_NAME']
        data_type = col['DATA_TYPE']
        column_type = col['COLUMN_TYPE']
        is_nullable = col['IS_NULLABLE'] == 'NO'
        column_key = col['COLUMN_KEY']
        column_default = col['COLUMN_DEFAULT']
        extra = col['EXTRA']

        pg_type, _ = mysql_to_pg_type(column_type, data_type, col['IS_NULLABLE'], column_key, column_default, extra)
        definition = f'{quote_ident(name)} {pg_type}'

        if is_nullable:
            definition += ' NOT NULL'
        if column_default is not None and column_default != 'CURRENT_TIMESTAMP':
            definition += f" DEFAULT {column_default}"
        if extra and 'auto_increment' in extra.lower():
            definition += ' GENERATED BY DEFAULT AS IDENTITY'

        if column_key == 'PRI':
            pk_columns.append(name)

        column_defs.append(definition)

    if pk_columns:
        column_defs.append(f"PRIMARY KEY ({', '.join(quote_ident(c) for c in pk_columns)})")

    stmt_parts.append(', '.join(column_defs))
    stmt_parts.append(')')
    sql_text = ' '.join(stmt_parts)
    with pg_conn.cursor() as cur:
        cur.execute(sql_text)


def copy_table(mysql_conn, pg_conn, schema: str, table: str) -> None:
    columns = get_mysql_columns(mysql_conn, schema, table)
    if not columns:
        return

    create_postgres_table(pg_conn, table, columns)

    column_names = [col['COLUMN_NAME'] for col in columns]
    quoted_names = ', '.join(quote_ident(name) for name in column_names)
    placeholders = ', '.join(['%s'] * len(column_names))

    with mysql_conn.cursor(pymysql.cursors.DictCursor) as source_cur:
        source_cur.execute(f'SELECT * FROM `{table}`')
        rows = source_cur.fetchall()

    if not rows:
        return

    with pg_conn.cursor() as target_cur:
        insert_sql = f'INSERT INTO {quote_ident(table)} ({quoted_names}) VALUES ({placeholders})'
        target_cur.executemany(insert_sql, [tuple(row.get(name) for name in column_names) for row in rows])


def get_mysql_tables(connection, schema: str) -> List[str]:
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT table_name FROM information_schema.tables WHERE table_schema = %s AND table_type = 'BASE TABLE' ORDER BY table_name",
            (schema,),
        )
        return [row[0] for row in cursor.fetchall()]


def migrate() -> None:
    mysql_host = get_env('MYSQL_HOST', 'localhost')
    mysql_port = int(get_env('MYSQL_PORT', '3306'))
    mysql_user = get_env('MYSQL_USER', 'root')
    mysql_password = get_env('MYSQL_PASSWORD', '')
    mysql_database = get_env('MYSQL_DATABASE')
    if not mysql_database:
        raise SystemExit('MYSQL_DATABASE is required')

    pg_host = get_env('POSTGRES_HOST', 'localhost')
    pg_port = int(get_env('POSTGRES_PORT', '5432'))
    pg_user = get_env('POSTGRES_USER', 'postgres')
    pg_password = get_env('POSTGRES_PASSWORD', 'postgres')
    pg_database = get_env('POSTGRES_DB', mysql_database)

    include_tables = parse_csv_list(get_env('TABLES'))
    skip_tables = parse_csv_list(get_env('SKIP_TABLES'))

    mysql_conn = pymysql.connect(
        host=mysql_host,
        port=mysql_port,
        user=mysql_user,
        password=mysql_password,
        database=mysql_database,
        charset='utf8mb4',
        cursorclass=pymysql.cursors.DictCursor,
    )

    pg_conn = psycopg2.connect(
        host=pg_host,
        port=pg_port,
        user=pg_user,
        password=pg_password,
        dbname=pg_database,
    )

    try:
        mysql_conn.ping(reconnect=False)
        pg_conn.autocommit = False

        tables = get_mysql_tables(mysql_conn, mysql_database)
        tables = [table for table in tables if table not in skip_tables]
        if include_tables:
            tables = [table for table in tables if table in include_tables]

        print(f'Migrating {len(tables)} tables from MySQL database {mysql_database}...')
        for table in tables:
            print(f'-> {table}')
            copy_table(mysql_conn, pg_conn, mysql_database, table)
        pg_conn.commit()
        print('Migration completed successfully.')
    except Exception as exc:
        pg_conn.rollback()
        raise exc
    finally:
        mysql_conn.close()
        pg_conn.close()


if __name__ == '__main__':
    try:
        migrate()
    except KeyboardInterrupt:
        print('Interrupted by user.', file=sys.stderr)
        sys.exit(130)
    except Exception as exc:
        print(f'Error: {exc}', file=sys.stderr)
        sys.exit(1)
