spring.application.name=administracion
server.port=8052

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_administracion}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:UnaClaveSuperSecretaYMuyLargaParaPoderFirmarElTokenCorrectamente12345}

ms.auth.base-url=${MS_AUTH_BASE_URL:http://localhost:8051}
internal.api.token=${INTERNAL_API_TOKEN:dev-internal-token}
ms.administracion.base-url=${MS_ADMINISTRACION_BASE_URL:http://localhost:8052}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
